### PR TITLE
Add `--fen` support across `play`, `pvp`, `watch`, and `calculate-best-move` (new)

### LINKED ISSUE #1: Add an example showing how to get best move from FEN

### PR DESCRIPTION
**Pull request by codyjk**
Resolves #1.

* Adds CLI support for passing in a `--fen` for any of the gameplay commands
* Introduces a `calculate-best-move` command that returns the best move from the given position (`--fen`) and `--depth` (default 4).

Example:

```console
$ chess calculate-best-move --fen "1Q6/8/8/8/8/k1K5/8/8 w - - 0 1"
Qb3#
```

Here are the complete CLI docs, for posterity:

```console
$ chess --help

chess 1.0.0
A classical chess engine implemented in Rust ♛

USAGE:
    chess <SUBCOMMAND>

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

SUBCOMMANDS:
    calculate-best-move        Use the chess engine to determine the best move from a given position, provided in
                               FEN notation with `--fen` (required). You can optionally specify the depth of the
                               search with the `--depth` arg (default: 4).
    count-positions            Count the number of possible positions for a given `--depth` (default: 4), and
                               reports the time it took to do so. By default, this searches all possible positions.
                               The routine can be run with alpha-beta pruning by selecting `--strategy alpha-beta`.
    determine-stockfish-elo    Determine the ELO rating of the engine at a given `--depth` (default: 4) and
                               `--starting-elo` (default: 1000). The engine will increment the Stockfish ELO until
                               it plateaus at a 50% win rate, at which point the rating is reported.
    help                       Prints this message or the help of the given subcommand(s)
    play                       Play a game against the computer, which will search for the best move using alpha-
                               beta pruning at the given `--depth` (default: 4). Your starting color will be
                               chosen at random unless you specify with `--color`. The initial position can be
                               specified using FEN notation with `--fen` (default: starting position).
    pvp                        Play a game against another human on this local machine. The initial position can be
                               specified using FEN notation with `--fen` (default: starting position).
    watch                      Watch the computer play against itself at the given `--depth` (default: 4). The
                               initial position can be specified using FEN notation with `--fen` (default: starting
                               position).
```

### CODE REVIEW

**Comment by brandonros** [comment]
looks great, can you make the output be UCI format?

```
$ chess calculate-best-move --fen "1Q6/8/8/8/8/k1K5/8/8 w - - 0 1"
Qb3#
```

I'm not quite sure if that is UCI?

**Comment by brandonros** [comment]
Also could you share some info on what a realistic maximum depth is (is there parallel iteration) and if it really improves ELO / play? For example, I'm lead to believe after about 8 it'll take very long.

**Comment by codyjk** [comment]
> Also could you share some info on what a realistic maximum depth is (is there parallel iteration) and if it really improves ELO / play? For example, I'm lead to believe after about 8 it'll take very long.

It depends on the hardware and position, but realistically 5 or 6 is reasonable for getting a good move in the early/mid game, and higher after that. Beyond that it starts to drop off pretty significantly.

Can you tell me more about your use case? I have a lot of ideas for how to improve performance and can probably squeeze another order of magnitude out without significant changes, but I just want to make sure I tailor my efforts accordingly depending on what you're looking for!

**Comment by brandonros** [comment]
@codyjk 

https://github.com/brandonros/chess_engine_api

I have this hooked up to a script that polls Lichess `fen`

I don't know how to play chess but my friends like it (and they don't know how to code) so it helps us bridge a gap and play together/try different settings + strategies.

If you can make it output `UCI`, I'll give it a go. My friend recently beat `depth 5` of Rustic, but I never thought to turn the depth up the longer the game goes on. Any suggestions?

Sounds like depth 6 for the first 5 moves. Should I ever go above 10? Depth 12-15 even if only a few pieces are left will probably take a while?

**Comment by codyjk** [comment]
@brandonros 

Thanks for the detail, and sorry for the late response!

> If you can make it output UCI, I'll give it a go. My friend recently beat depth 5 of Rustic, but I never thought to turn the depth up the longer the game goes on. Any suggestions?

I should be able to make the interface UCI, let me try to get to this in the near future.

Shallower depths for mid-game often get the job done, but in late game a lot of the gameplay is focused on pawn and king movements, and developing the position often takes much longer than 4-5 moves. So, it makes sense to use a higher depth during that part of the game. The search space is also usually a lot smaller at that point so it typically doesn't take any more time when increasing the depth.

> Sounds like depth 6 for the first 5 moves. Should I ever go above 10? Depth 12-15 even if only a few pieces are left will probably take a while?

A few thoughts:
* The engine will attempt to play [book moves](https://github.com/codyjk/RustChess/blob/67297a989e7e85b2d17ff2b8c75ea2f8efb8f05f/opening_lines.txt) for the few moves. It does not perform alpha-beta search until the position falls out of book.
* Depending on skill level, depth 5-6 should be sufficient for getting a quality move during the midgame. For reference, I play at roughly 1400-1500 ELO, and I find it very difficult to beat the engine at this depth.
* For the reasons I mentioned above, you could probably change this to somewhere around 7-8 during the endgame. If you want a simple endgame heuristic, see the logic the engine uses [here](https://github.com/codyjk/RustChess/blob/67297a989e7e85b2d17ff2b8c75ea2f8efb8f05f/src/evaluate/mod.rs#L161-L184). 
* Right now depths 8 and above can cause really poor performance for a number of reasons. I'm slowly improving how the search is factored to squeeze out a lot of performance but I wouldn't expect to see any big changes soon - this is a personal project that is relegated to free time at the moment 😅 - but I have a few clear strategies in the works for getting another order of magnitude or more out of the engine (proper transposition table, null moves, improve memory layout of key data structures)

On the other hand, rather than continually change the depth, one other idea I had is to give the option to provide a `--maximum-search-duration-ms` param that constrains the best move search to some duration (e.g. `1000` if you want a response in under 1s). With this approach the engine would do as much as it could within the given duration - first depth 1, then depth 2, then depth 3, etc... until it ran out of time. That way you never would need to change the depth, and naturally as the game progresses you would achieve deeper searches without having to tune anything. Would you find this idea useful?

In any case, let me know your thoughts!

**Pull request merged**
